[package]
name = "validation-tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indexmap = "2.2.2"
serde = { version = "1.0", features = ["derive"] }
