[package]
name = "validation-tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
validator = { version = "0.16", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
